### ISSUE TITLE
Unable to start metasploit-framework on Fedora 40 - libcrypt.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by iRomanyshyn** [rapid7/metasploit-framework#19175]
## Steps to reproduce

1. Install using `https://docs.metasploit.com/docs/using-metasploit/getting-started/nightly-installers.html#installing-metasploit-on-linux--macos`
2. Try to run `msfconsole` and get the error: ```/opt/metasploit-framework/bin/../embedded/bin/ruby: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory```

### Environment

Fedora 40

### Metasploit version

Framework: 6.4.8-dev-
Console  : 6.4.8-dev-

### How I fixed this

`sudo dnf install libxcrypt-compat`

**Comment by misaelnieto** [comment]
```
sudo dnf install libxcrypt-compat
```
Fixed the issue.

**Comment by q2dg** [comment]
Please, add this package (libxcrypt-compat) as a dependency to install in Fedora systems in Metasploit installer script, please

**Comment by osamsam321** [comment]
Had to uninstall and reinstall libxcrypt-compat on Fedora 41.

**Comment by iRomanyshyn** [comment]
The issue persists. Today, I had the same experience. Thanks god someone (me from the past) described what to install to make it work.
